version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "temp/**",
  "example/**",
  "outputs/**",
  "results/**",
  "notebooks/**",
  "**/__pycache__/**",
  "*.pyc"
]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[code_formatters]]
name = "ruff"