[project]
name = "pmf-tsfm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chronos-forecasting>=2.1.0",
    "dvc>=3.43.1",
    "hydra-core>=1.3.0",
    "numpy>=1.26.4",
    "pandas>=2.1.4",
    "pm4py>=2.7.19",
    "seaborn>=0.13.2",
    "uni2ts>=1.2.0",
]
